import "./termCondition.css";

import Footer2 from "../compontent/Footer/Footer2";
import Navbar from "../compontent/Navbar/Navbar";
import { Banner4 } from "../compontent/Banner/Banner";
const termsSections = [
  {
    title: "Introduction and Acceptance of Terms",
    content: `
      Welcome to Frek App LLC! These Terms and Conditions ("Terms") outline the rules 
      and regulations for the use of Frek App LLC's Website, located at www.thefrekapp.com.
      By accessing this website or using our services, we assume you accept these Terms.
      Do not continue to use Frek App LLC if you do not agree to all of the Terms stated on this page.
    `,
    subContent: `
  We use Your Personal data to provide and improve the Service. By using the Service, You agree to the 
   collection and use of information in accordance with this Privacy Policy.
  `,
    subPoints: [
      "These Terms apply to all visitors and users of the service.",
      "Please ensure you understand these Terms before proceeding.",
    ],
  },
  {
    title: "Interpretation",
    content: `
     The words of which the initial letter is capitalized have meanings defined under the following conditions. 
The following definitions shall have the same meaning regardless of whether they appear in singular or 
in plural.
    `,
    subContent: `
For the purposes of this Privacy Policy:
  `,
    subPoints: [
      "Account means a unique account created for You to access our Service or parts of our Service.",
      "Company (referred to as either 'the Company', 'We', 'Us' or 'Our' in this Agreement) refers to Frek App LLC, 3133 MAPLE DR. STE 240 ATLANTA , GA 30305.",
      "Cookies are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.",
      "Country refers to: North America, USA.",
      "Device means any device that can access the Service such as a computer, a cellphone or a digital tablet.",
      "Service refers to the Website and/or App.",
      "Service Provider means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.",
      "Third-party Social Media Service refers to any website or any social network website through which a User can log in or create an account to use the Service.",
      "Usage Data refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).",
      "Website refers to Frek App LLC, accessible from www.thefrekapp.com.",
      "You means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.",
    ],
  },
  {
    title: "Personal Data",
    content: `
  While using Our Service, We may ask You to provide Us with certain personally identifiable information 
that can be used to contact or identify You. Personally identifiable information may include, but is not 
limited to
    `,
    subPoints: [
      "Email address",
      "First name and last name",
      "Phone number",
      "Usage Data",
    ],
  },
  {
    title: "Usage Data",
    content: `
      Usage Data is collected automatically when using the Service.
Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), 
browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, 
the time spent on those pages, unique device identifiers and other diagnostic data.
    `,
    subContent: `
     When You access the Service by or through a mobile device, We may collect certain information 
automatically, including, but not limited to, the type of mobile device You use, Your mobile device 
unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile 
Internet browser You use, unique device identifiers and other diagnostic data.

    `,

    lastPoint: `
    We may also collect information that Your browser sends whenever You visit our Service or when You 
access the Service by or through a mobile device.
    `,
  },
  {
    title: "Tracking Technologies and Cookies",
    content: `
      We use Cookies and similar tracking technologies to track the activity on Our Service and store certain 
information. Tracking technologies used are beacons, tags, and scripts to collect and track information 
and to improve and analyze Our Service.
    `,
    subContent: `
   You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, 
if You do not accept Cookies, You may not be able to use some parts of our Service.
Cookies can be "Persistent" or "Session" Cookies. Persistent Cookies remain on Your personal computer 
or mobile device when You go offline, while Session Cookies are deleted as soon as You close Your web 
browser.
We use both Session and Persistent Cookies for the purposes set out below:

    `,
    subPoints: [
      "Necessary / Essential Cookies",
      "Functionality Cookies",
      "Analytical / Performance Cookies",
      "Targeting Cookies",
    ],

    lastPoint: `
    For more information about the cookies we use and your choices regarding cookies, please visit our
Cookies Policy.
    `,
  },
  {
    title: "Content Liability",
    content: `
      We shall not be held responsible for any content that appears on your Website. You agree to protect 
      and defend us against all claims arising from your Website.
    `,
  },
  {
    title: "Use of Your Personal Data",
    content: `
     The Company may use Personal Data for the following purposes:
    `,
    subPoints: [
      "To provide and maintain our Service, including to monitor the usage of our Service.",
      "To manage Your Account: to manage Your registration as a user of the Service. The Personal Data You provide can give You access to different functionalities of the Service that are available to You as a registered user.",
      "For the performance of a contract: the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased or of any other contract with Us through the Service.",
      "To contact You: To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile application's push notifications regarding updates or informative communications related to the functionalities, products or contracted services, including the security updates, when necessary or reasonable for their implementation.",
      "To provide You with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless You have opted not to receive such information.",
      "To manage Your requests: To attend and manage Your requests to Us.",
      "For business transfers",
      "For other purposes such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns and to evaluate and improve our Service, products, services, marketing and your experience.",
    ],
  },
  {
    content: `
    We may share Your personal information in the following situations:
    `,
    subPoints: [
      "With Service Providers",
      "With business partners",
      "With Affiliates: We may share Your information with Our affiliates, in which case we will require those affiliates to honor this Privacy Policy.",
      "With other users: when You share personal information or otherwise interact in the public areas with other users, such information may be viewed by all users and may be publicly distributed outside.",
      "With Your consent: We may disclose Your personal information for any other purpose with Your consent.",
    ],
  },
  {
    title: "Retention of Your Personal Data",
    content: `
      The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in 
this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our 
legal obligations, resolve disputes, and enforce our legal agreements and policies.
    `,
  },
  {
    title: "Transfer of Your Personal Data",
    content: `
      Your information, including Personal Data, is processed at the Company's operating offices and in any 
other places where the parties involved in the processing are located. It means that this information 
may be transferred to — and maintained on — computers located outside of Your state, province, 
country or other governmental jurisdiction where the data protection laws may differ than those from 
Your jurisdiction.
    `,
    subContent: `
      Your consent to this Privacy Policy followed by Your submission of such information represents
      Your agreement to that transfer.
    `,
  },
  {
    title: "Business Transactions",
    content: `
      If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred
    `,
  },
  {
    title: "Law enforcement",
    content: `
      Under certain circumstances, the Company may be required to disclose Your Personal Data if required to 
do so by law or in response to valid requests by public authorities.
    `,
  },
  {
    title: "Other legal requirements",
    content: `
      The Company may disclose Your Personal Data in the good faith belief that such action is necessary to:
    `,
    subPoints: [
      "Comply with a legal obligation",
      "Protect and defend the rights or property of the Company ",
      "Prevent or investigate possible wrongdoing in connection with the Service ",
      "Protect the personal safety of Users of the Service or the public ",
      "Protect against legal liability ",
    ],
  },
  {
    title: "Security of Your Personal Data",
    content: `
      The security of Your Personal Data is important to Us, but remember that no method of transmission 
over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially 
acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.
    `,
  },
  {
    title: "Links to Other Websites",
    content: `
      Our Service may contain links to other websites that are not operated by Us. We strongly advise You to 
review the Privacy Policy of every site You visit.
    `,
  },
  {
    title: "Changes to this Privacy Policy",
    content: `
     We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the 
new Privacy Policy on this page and update the "Last updated" date at the top of this Privacy Policy.
You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy 
are effective when they are posted on this page.
    `,
  },
  {
    title: "Children's Privacy",
    content: `
  Our Service does not address anyone under the age of 18. We do not knowingly collect personally 
identifiable information from anyone under the age of 18. If You are a parent or guardian and You are 
aware that Your child has provided Us with Personal Data, please contact Us. If We become aware that 
We have collected Personal Data from anyone under the age of 18 without verification of parental 
consent, We take steps to remove that information from Our servers.
    `,
  },
  {
    title: "Contact Us",
    content: `
      If you have any questions about this Privacy Policy, You can contact us:
    `,
    subPoints: [
      "By email: frekappllc@gmail.com",
      "By visiting this page on our web www.thefrekapp.com",
    ],
  },
];

const Privacy = () => {
  return (
    <>
      <Navbar />
      <Banner4 />
      <div className="policy">
        <div className="policy-data">
          <p>Last Updated: 09 January 2025</p>
          <p>
            Please read these terms and conditions carefully before using Our
            Service.
          </p>
          {termsSections.map((section, index) => (
            <div key={index} className="policy-section">
              <h2>{section.title}</h2>
              <p>{section.content}</p>
              <p>{section.subcontent}</p>
              {section.subPoints && section.subPoints.length > 0 && (
                <ul className="sub-points">
                  {section.subPoints.map((point, subIndex) => (
                    <li key={subIndex}>{point}</li>
                  ))}
                </ul>
              )}
              {section.lastpoint && <p>{section.lastpoint}</p>}
            </div>
          ))}
        </div>
      </div>
      <Footer2 />
    </>
  );
};

export default Privacy;
